### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by akamob** [yuanher/GaitRecognition#1]
Hi, Thank you for the great work.

When I run to:
```
import glob, os

basedir = "/content"
tempOutputFile = "/content/temp.avi"
os.chdir(basedir)

for file in files_to_process:
  filename = os.path.splitext(os.path.basename(file))[0]
  filename_split = filename.split("_")
  subject = filename_split[0]

  if(len(filename_split) == 2):
    repetition = "R" + filename_split[1][-1]
  else:
    repetition = "R" + filename_split[1][-1] + filename_split[2] 
  print(filename, subject, repetition)

  !rm {tempOutputFile}
  !mkdir -p {basedir}/output/OpenPose/{subject}/{repetition}
  os.chdir("/content/openpose")

  #!ffmpeg -y -loglevel info -i '{file}' -t 10 /content/video.mp4
  
  !./build/examples/openpose/openpose.bin --video '{file}' --write_json {basedir}/output/OpenPose/{subject}/{repetition} --display 0  --write_video {tempOutputFile}
  # convert the result into MP4
  !ffmpeg -y -loglevel info -i {tempOutputFile} {basedir}/output/OpenPose/{subject}/{repetition}/{filename}.mp4
```
I got this error:
```
IndexError                                Traceback (most recent call last)
<ipython-input-11-f301ba4400ee> in <module>()
     13     repetition = "R" + filename_split[1][-1]
     14   else:
---> 15     repetition = "R" + filename_split[1][-1] + filename_split[2]
     16   print(filename, subject, repetition)
     17 

IndexError: list index out of range
```
![q1](https://user-images.githubusercontent.com/49118957/166671055-d1fd1f5f-e955-4685-9947-c743f3c6767f.jpg)

May I have your suggestions to fix this problem?
Any help is much appreciated:)

**Comment by yuanher** [comment]
The if statement handles filenames without direction label e.g. **S042_T3.avi** whilst the else statement handles filenames with direction label (L/R) e.g. **S042_T1_R.avi.**

**Comment by akamob** [comment]
Hi, thank you for the quick reply:)

I check the dataset (gprg4s73v4-2.zip), these folders are named follow to the rules. But openpose stopped at S001/R1R:
![Q2](https://user-images.githubusercontent.com/49118957/166715611-527458ae-89e3-4b44-bc58-57d51341a816.jpg)

I am not sure what happened.

**Comment by akamob** [comment]
Hi, Thank you for the great work.

I have solved my problem and I can run your code, train and save OpenPose/AlphaPose model. Thank you for your detailed comment:) 

I will research your work and do more tests, if I have some new problems then I would contact you again.
Thank you!

**Comment by akamob** [comment]
Hi, @yuanher,

Recently I created my own dataset and trained an AlphaPose model, I replaced the related files with my training model such as shown in the following figure.
![1](https://user-images.githubusercontent.com/49118957/173287748-c9dc553f-b9d6-46d8-b4a2-9a473e52a215.jpg)

However, when I open the web app and upload the video to test model, I met this error:
```
json.decoder.JSONDecodeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AppLogs\yi\envs\tfyi\Lib\site-packages\flask\app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\AppLogs\yi\envs\tfyi\Lib\site-packages\flask\app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "C:\AppLogs\yi\envs\tfyi\Lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\AppLogs\yi\envs\tfyi\Lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\AppLogs\yi\envs\tfyi\Lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\AppLogs\yi\envs\tfyi\Lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\益誠\Desktop\GaitRecognition-main\Web_App\app\main.py", line 134, in predict
    loaded_model = tf.keras.models.load_model('model')
  File "C:\AppLogs\yi\envs\tfyi\Lib\site-packages\tensorflow\python\keras\saving\save.py", line 187, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "C:\AppLogs\yi\envs\tfyi\Lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 120, in load
    model = tf_load.load_internal(
  File "C:\AppLogs\yi\envs\tfyi\Lib\site-packages\tensorflow\python\saved_model\load.py", line 632, in load_internal
    loader = loader_cls(object_graph_proto, saved_model_proto, export_dir,
  File "C:\AppLogs\yi\envs\tfyi\Lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 194, in __init__
    super(KerasObjectLoader, self).__init__(*args, **kwargs)
  File "C:\AppLogs\yi\envs\tfyi\Lib\site-packages\tensorflow\python\saved_model\load.py", line 130, in __init__
    self._load_all()
  File "C:\AppLogs\yi\envs\tfyi\Lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 215, in _load_all
    self._layer_nodes = self._load_layers()
  File "C:\AppLogs\yi\envs\tfyi\Lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 315, in _load_layers
    layers[node_id] = self._load_layer(proto.user_object, node_id)
  File "C:\AppLogs\yi\envs\tfyi\Lib\site-packages\tensorflow\python\keras\saving\saved_model\load.py", line 323, in _load_layer
    metadata = json_utils.decode(proto.metadata)
  File "C:\AppLogs\yi\envs\tfyi\Lib\site-packages\tensorflow\python\keras\saving\saved_model\json_utils.py", line 60, in decode
    return json.loads(json_string, object_hook=_decode_helper)
  File "C:\AppLogs\yi\envs\tfyi\Lib\json\__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "C:\AppLogs\yi\envs\tfyi\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\AppLogs\yi\envs\tfyi\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I hvae trained different AlphaPose models (stacked and bidirectional) and replaced your model with all downloaded files, but I still encountered the above problems.

May I have your suggestions to fix this problem?
Any help is much appreciated!
